title: Objects
modelClass: NielsVanDenDries\FieldEngineeringToolkit\Models\Objects
list: $/nielsvandendries/fieldengineeringtoolkit/models/objects/columns.yaml
recordUrl: 'nielsvandendries/fieldengineeringtoolkit/objects/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
