title: Jobs
modelClass: NielsVanDenDries\FieldEngineeringToolkit\Models\Jobs
list: $/nielsvandendries/fieldengineeringtoolkit/models/jobs/columns.yaml
recordUrl: 'nielsvandendries/fieldengineeringtoolkit/jobs/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
