title: Settings
modelClass: NielsVanDenDries\FieldEngineeringToolkit\Models\Settings
list: $/nielsvandendries/fieldengineeringtoolkit/models/settings/columns.yaml
recordUrl: 'nielsvandendries/fieldengineeringtoolkit/settings/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
