title: RideRegistration
modelClass: NielsVanDenDries\FieldEngineeringToolkit\Models\RideRegistration
list: $/nielsvandendries/fieldengineeringtoolkit/models/rideregistration/columns.yaml
recordUrl: 'nielsvandendries/fieldengineeringtoolkit/rideregistration/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
