title: Projects
modelClass: NielsVanDenDries\FieldEngineeringToolkit\Models\Projects
list: $/nielsvandendries/fieldengineeringtoolkit/models/projects/columns.yaml
recordUrl: 'nielsvandendries/fieldengineeringtoolkit/projects/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
